module-template: ! 'module MODULE_NAME where

'
extensions:
  GeneralizedNewtypeDeriving: true
  TemplateHaskell: true
  OverloadedStrings: true
  GADTs: true
  EmptyDataDecls: true
  ImplicitPrelude: false
  QuasiQuotes: true
  TypeFamilies: true
  MonomorphismRestriction: false
  DeriveDataTypeable: true
  CPP: true
  MultiParamTypeClasses: true
  FlexibleContexts: true
environment: null
cabal-file: project.cabal
modules:
  GeneralFunctions:
    filename: GeneralFunctions.hs
  Application:
    filename: Application.hs
  Settings:
    filename: Settings.hs
  Settings.Development:
    filename: Settings/Development.hs
  Foundation:
    filename: Foundation.hs
  Handler.Admin:
    filename: Handler/Admin.hs
  Model:
    filename: Model.hs
  Handler.AdminBlog:
    filename: Handler/AdminBlog.hs
  Main(app/main.hs):
    filename: app/main.hs
  Import:
    filename: Import.hs
  Handler.Blog:
    filename: Handler/Blog.hs
  Handler.About:
    filename: Handler/About.hs
  Settings.StaticFiles:
    filename: Settings/StaticFiles.hs
  Main(devel.hs):
    filename: devel.hs
version: 1
ghc-args: []
