# -- Admin Page Titles
TitleAdminDashboard: Dashboard
TitleAdminBlogArticles: Blog Articles
TitleAdminNewArticle: New Article
TitleAdminUpdateArticle: Update Article
TitleAdminTrashArticles: Trashed Articles


# -- Admin Messages
MsgPublishedArticle title@Text: Published Article: #{title}
MsgUnpublishedArticle title@Text: Unpublished Article: #{title}
MsgDeletedArticle title@Text: Deleted Article: #{title}
MsgSavedArticle title@Text: Saved Article: #{title}
MsgCreatedArticle title@Text: Created Article: #{title}
MsgCreatedArticleGistError title@Text: Created Article: #{title}. Something went wrong when creating the gist!


# -- Admin Breadcrumbs
CrumbDashboard: Dashboard
CrumbArticles: Articles
CrumbTrashedArticles: Trashed Articles
CrumbNewArticle: New Article
CrumbUpdated title@Text: Updated: #{title}
CrumbTrashed title@Text: Trashed: #{title}
CrumbUnpublished title@Text: Unpublished: #{title}
CrumbPublished title@Text: Published: #{title}


# -- admin-layout AND admin/articles 
Articles: Articles


# -- admin-layout
Dashboard: Dashboard
NewArticle: New Article
Settings: Settings
Trash: Trash
Logout: Logout


# -- admin/articles
TrashedArticles: Trashed Articles
NoTrash: No trash yet :)
NoArticles: No articles yet! :(
SearchTitles: Search titles...
ByLower: by
DeleteArticle: Delete Article
UnpublishArticle: Unpublish Article
PublishArticle: Publish Article
ViewArticle: View Article
EditArticle: Edit Article


# -- admin/create-article
ArticleTitlePlaceholder: The article title
ContentPlaceholder: Some nice content to go with that title!
DashedArticleTitle: the-article-title
Markdown: Markdown
MarkdownCheatsheet: Markdown Cheatsheet
Close: Close
Preview: Preview
LowerWord: word
LowerWords: words
Update: Update
Unpublish: Unpublish
SaveDraft: Save Draft
Publish: Publish

MarkdownCheatsheetExplanation: You can always use plain HTML instead of markdown. This is often handy for sizing images with width and height attributes. This will give a brief overview, but for a more extensive guide, take a look at
MarkdownSyntax: Markdown Syntax
MarkdownLargeHeading: Large heading
MarkdownBoldText: Bold text
MarkdownAndSmallerHeading: And smaller
MarkdownItalicizedText: Italicized text
MarkdownLinks: Links
MarkdownLinksWithTitle: And links with title
MarkdownImages: Images
MarkdownImagesWithTitle: Images with title
MarkdownUnorderedLists: Unordered lists
MarkdownUnorderedListsExtra: you can substitute * with + or -
MarkdownOrderedLists: Ordered lists
MarkdownOrderedListsExtra: note that the numbering doesn't matter, as long as there is a period after
MarkdownCodeBlock: Code block
MarkdownInlineCode: Inline-code



# -- admin/dashboard
Analytics: Analytics
AuthorStatistics: Author Statistics
CommentStatistics: Comment Statistics
SystemInformation: System Information