# -------------- Admin Page Titles -------------- #
TitleAdminDashboard: Dashboard
TitleAdminBlogArticles: Blog Articles
TitleAdminNewArticle: New Article
TitleAdminUpdateArticle: Update Article
TitleAdminTrashArticles: Trashed Articles
TitleAdminStaticPages: Pages
TitleAdminNewStaticPage: New Page
TitleAdminUpdateStaticPage: Update Page
TitleAdminTrashStaticPages: Trashed Pages


# -------------- Admin Messages -------------- #
MsgPublishedArticle title@Text: Published Article: #{title}
MsgUnpublishedArticle title@Text: Unpublished Article: #{title}
MsgDeletedArticle title@Text: Deleted Article: #{title}
MsgSavedArticle title@Text: Saved Article: #{title}
MsgCreatedArticle title@Text: Created Article: #{title}
MsgCreatedArticleGistError title@Text: Created Article: #{title}. Something went wrong when creating the gist!
MsgPublishedStaticPage title@Text: Published Page: #{title}
MsgUnpublishedStaticPage title@Text: Unpublished Page: #{title}
MsgDeletedStaticPage title@Text: Deleted Page: #{title}
MsgSavedStaticPage title@Text: Saved Page: #{title}
MsgCreatedStaticPage title@Text: Created Page: #{title}
MsgCreatedStaticPageGistError title@Text: Created Page: #{title}. Something went wrong when creating the gist!


# -------------- Breadcrumbs -------------- #
CrumbAdminDashboard: Dashboard
CrumbAdminUpdated title@Text: Updated: #{title}
CrumbAdminTrashed title@Text: Trashed: #{title}
CrumbAdminUnpublished title@Text: Unpublished: #{title}
CrumbAdminPublished title@Text: Published: #{title}

CrumbAdminArticles: Articles
CrumbAdminTrashedArticles: Trashed Articles
CrumbAdminNewArticle: New Article
CrumbAdminStaticPages: Pages
CrumbAdminTrashedStaticPages: Trashed Pages
CrumbAdminNewStaticPage: New Page


# -------------- admin-layout AND admin/list-content -------------- #
Articles: Articles
Article: Article
Pages: Pages
Page: Page


# -------------- admin-layout -------------- #
Dashboard: Dashboard
NewArticle: New Article
NewPage: New Page
Settings: Settings
Trash: Trash
Logout: Logout


# -------------- admin/create-content AND admin/list-content -------------- #
Unpublish: Unpublish
Publish: Publish


# -------------- admin/list-content -------------- #
SearchTitles: Search titles...
LowerBy: by
NoTrash: No trash yet :)
Delete': Delete
View: View
Edit: Edit
Trashed: Trashed

NoArticles: No articles yet! :(
NoPages: No pages yet! :(


# -------------- admin/create-content -------------- #
TitlePlaceholder: The title
ContentPlaceholder: Some nice content to go with that title!
Markdown: Markdown
MarkdownCheatsheet: Markdown Cheatsheet
Close: Close
Preview: Preview
LowerWord: word
LowerWords: words
Update: Update
SaveDraft: Save Draft


# -------------- admin/markdown-cheatsheet -------------- #
MarkdownCheatsheetExplanation: You can always use plain HTML instead of markdown. This is often handy for sizing images with width and height attributes. This will give a brief overview, but for a more extensive guide, take a look at
MarkdownSyntax: Markdown Syntax
MarkdownLargeHeading: Large heading
MarkdownBoldText: Bold text
MarkdownAndSmallerHeading: And smaller
MarkdownItalicizedText: Italicized text
MarkdownLinks: Links
MarkdownLinksWithTitle: And links with title
MarkdownImages: Images
MarkdownImagesWithTitle: Images with title
MarkdownUnorderedLists: Unordered lists
MarkdownUnorderedListsExtra: you can substitute * with + or -
MarkdownOrderedLists: Ordered lists
MarkdownOrderedListsExtra: note that the numbering doesn't matter, as long as there is a period after
MarkdownCodeBlock: Code block
MarkdownInlineCode: Inline-code



# -------------- admin/dashboard -------------- #
CloudFlareAnalytics: CloudFlare Analytics
CloudFlareAnalyticsInterval: Time Interval: 30 days
CloudFlareAnalyticsLoading: Loading Data...
CloudFlareAnalyticsPageViews: Page Views
CloudFlareAnalyticsVisitors: Visitors
CloudFlareAnalyticsUniqueVisitors: Unique Visitors
CloudFlareAnalyticsRegular: Regular
CloudFlareAnalyticsCrawler: Crawler
CloudFlareAnalyticsThreat: Threat
AuthorStatistics: Author Statistics
CommentStatistics: Comment Statistics
SystemInformation: System Information
