exec: ../dist/build/HsCMS/HsCMS
args:
    - production
ssl: false

# This will become APPROOT, if you have any absolute URLs, it 
# must be accurate
host: yoursite.com

# https://github.com/yesodweb/yesod/wiki/Deploying-via-Keter-alongside-Nginx#wiki-double-proxy
# The requests from nginx -> keter will not come to that 
# hostname (the host setting), so we need to tell keter 
# to listen on something else as well
# extra-hosts:
#     - "127.0.0.1:8000" 

static-hosts:
    - host: yoursite.com/static
      root: ../static # relative to config file, just like the executable

# Host name redirects. Completely optional
redirects:
    - from: www.yoursite.com
      to: yoursite.com

# Use the following to automatically copy your bundle upon creation via `yesod
# keter`. Uses `scp` internally, so you can set it to a remote destination
# copy-to: user@host:/opt/keter/incoming