Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: copyright tehnix 2014
  admins: []
  #disqus: disqus_shortname_for_testing
  #disqusSecretKey: your_disqus_secret_api_key
  #disqusAccessToken: your_disqus_access_token
  #cloudflareKey: cloudflare_api_key
  #cloudflareMail: "mail_associated_with_api_key@mail.com"
  #cloudflareZone: "example.com"
  #gistPublic: false
  #layout: "default-layout"

Development:
  <<: *defaults

Testing:
  port: 80
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://yoursite.com"
  #analytics: your_analytics_UA
  #disqus: disqus_shortname_for_production
  #githubToken: githuh_personal_accesss_token_with_gist_scope
  #gistPublic: true
  <<: *defaults
