#!/bin/bash -ex

cabal clean
cabal configure
cabal build

strip dist/build/HsCMS/HsCMS

rm -rf static/tmp/

# you can use this to tar directly into the incoming folder, but you 
# # need write access to it
# tar czfv - dist/build/yourapp/yourapp config static > /opt/keter/incoming/yourapp.keter
#
# # if you don't want to provide a normal user that access, you can split 
# # the command and use sudo on the mv
tar czfv HsCMS.keter dist/build/HsCMS/HsCMS config static
mv HsCMS.keter /opt/keter/incoming/
