exec: ../dist/build/HsCMS/HsCMS
args:
    - production
host: codetalk.io # This will be used as APPROOT
ssl: false

# Use the following to automatically copy your bundle upon creation via `yesod
# keter`. Uses `scp` internally, so you can set it to a remote destination
# copy-to: user@host:/opt/keter/incoming
copy-to: root@bit:/opt/keter/incoming

extra-hosts:
    - "127.0.0.1:8000" 

static-hosts:
    - host: codetalk.io/static
      root: ../static # relative to config file, just like the executable

# Host name redirects.
redirects:
    - from: www.codetalk.io
      to: codetalk.io
