Default: &defaults
  host: "*4"
  port: 3000
  approot: "http://localhost:3000"
  copyright: copyright tehnix 2012
  admins: ["christianlaustsen@gmail.com"]

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://codetalk.io"
  <<: *defaults
