Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: copyright tehnix 2013
  admins: ["christianlaustsen@gmail.com"]

Development:
  #approot: "http://devel.codetalk.io"
  #approot: "http://192.168.199.130:3000"
  #analytics: UA-19146082-5
  <<: *defaults

Testing:
  port: 80
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://codetalk.io"
  analytics: UA-19146082-5
  <<: *defaults
