Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: Copyright Christian Kjaer Laustsen
  admins: ["christianlaustsen@gmail.com", "matrix@codetalk.io", "sotd@codetalk.io", "kdj.1337@gmail.com", "iliekpenguinz@gmail.com"]
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://tehnix.codetalk.io"
  <<: *defaults
