Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: copyright tehnix 2014
  admins: []
  theme: default
  #disqus: disqus_shortname_for_testing
  #githubToken: githuh_personal_accesss_token_with_gist_scope

Development:
  <<: *defaults

Testing:
  port: 80
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://yoursite.com"
  #analytics: your_analytics_UA
  #disqus: disqus_shortname_for_production
  <<: *defaults
