Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  #approot: "http://localhost:3000"
  approot: "http://codetalk.io"
  copyright: Copyright Christian Kjaer Laustsen
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://codetalk.io"
  <<: *defaults
