Default: &defaults
  database: yesog.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: yesog_test.sqlite3
  <<: *defaults

Staging:
  database: yesog_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: yesog_production.sqlite3
  poolsize: 100
  <<: *defaults
