Default: &defaults
  database: HsCMS.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: HsCMS_test.sqlite3
  <<: *defaults

Staging:
  database: HsCMS_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: HsCMS_production.sqlite3
  poolsize: 100
  <<: *defaults
